apiVersion: v1
kind: ConfigMap
metadata:
  name: streamprocess-config
  namespace: streamprocess
data:
  REDIS_HOST: "redis-service"
  MINIO_ENDPOINT: "minio-service:9000"
  LOG_LEVEL: "INFO"
  WHISPER_MODEL_SIZE: "base"
  WHISPER_DEVICE: "cpu"
  OCR_LANG: "en,ch_sim"
  WORKER_CONCURRENCY: "4"
  BATCH_SIZE: "8"
  MAX_CONCURRENT_STREAMS: "100"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: streamprocess
  labels:
    app: grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: streamprocess:grpc-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: streamprocess-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          exec:
            command:
            - python3
            - -c
            - "import grpc; channel=grpc.insecure_channel('localhost:50051'); channel.close()"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python3
            - -c
            - "import grpc; channel=grpc.insecure_channel('localhost:50051'); channel.close()"
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: models
          mountPath: /app/models
          readOnly: true
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
  namespace: streamprocess
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-lb
  namespace: streamprocess
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    protocol: TCP
  type: LoadBalancer